const sections={galaxy:['01 / THE CONSTELLATION','每一句话，都有自己的坐标。','拖动旋转 · 滚轮缩放 · 点击星星重返那一刻'],mem:['02 / MEMORY CARDS','那些被好好记住的事。','保留原有分类、重要度与置顶标记'],digest:['03 / DAILY IMPRESSIONS','日子慢慢，留下了印象。','对话日历 · 周印象 · 日印象'],ledger:['04 / UNFINISHED THREADS','还挂在心上的，那些线索。','欠账与悬案合并 · 未结与已结分开收好'],idn:['05 / BECOMING','一点点，看清自己的形状。','已立格与候选池 · 缺陷、闪光与证据'],diary:['06 / BETWEEN THE PAGES','翻开某天，听见那时的心跳。','主日记与心跳线日记 · 点击展开全文']};
const originalLoad=window.loadPage,pendingPages={};window.loadPage=v=>{if(pendingPages[v])return pendingPages[v];pendingPages[v]=(async()=>{try{await originalLoad(v);if(v==='mem')addMemoryTools();makeAccessible();}catch(e){loaded[v]=false;const el=document.getElementById('p-'+v);el.innerHTML='<div class="loading">'+esc(e.message)+'<br><button class="retry">重新读取 ↗</button></div>';el.querySelector('button').onclick=()=>loadPage(v)}finally{delete pendingPages[v]}})();return pendingPages[v]};
document.querySelectorAll('#bar button').forEach(b=>b.addEventListener('click',()=>{const [code,title,note]=sections[b.dataset.v];document.getElementById('section-code').textContent=code;document.getElementById('section-title').textContent=title;document.getElementById('section-note').textContent=note;document.querySelectorAll('#bar button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))}));
async function lopiWander(){const b=document.getElementById('lopi-wander');b.disabled=true;document.getElementById('lopi-says').textContent='让我翻翻，一段记忆正在回来。';try{document.querySelector('[data-v="mem"]').click();await loadPage('mem');await wander({stopPropagation(){}});document.getElementById('lopi-says').textContent='找到了。去看看那时留下的话吧。';document.getElementById('wanderBox').scrollIntoView({behavior:'smooth',block:'center'});makeAccessible()}catch(e){document.getElementById('lopi-says').textContent='暂时没能翻到，请稍后再试。'}finally{b.disabled=false}}
document.getElementById('lopi-wander').onclick=lopiWander;document.getElementById('lopi-image').onclick=lopiWander;
document.getElementById('search-submit').onclick=()=>document.getElementById('gq').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));
function addMemoryTools(){const page=document.getElementById('p-mem');if(page.querySelector('.memory-tools'))return;const cards=[...page.querySelectorAll(':scope > .card')];const tool=document.createElement('div');tool.className='memory-tools';tool.innerHTML='<input aria-label="搜索记忆" placeholder="找一段记忆、一个词…"><select aria-label="记忆分类"><option value="">全部分类</option></select><select aria-label="置顶筛选"><option value="">全部记忆</option><option value="pin">只看置顶</option></select><span id="memory-count"></span>';page.prepend(tool);const grid=document.createElement('div');grid.className='memory-grid';cards.forEach(c=>grid.append(c));page.append(grid);const select=tool.querySelector('select');for(const cat of new Set(cards.map(c=>c.querySelector('.meta span:nth-child(2)')?.textContent))){if(cat){const o=document.createElement('option');o.value=cat;o.textContent=cat;select.append(o)}}function filter(){let n=0;for(const c of cards){c.hidden=!(c.textContent.toLowerCase().includes(tool.querySelector('input').value.trim().toLowerCase())&&(!select.value||c.querySelector('.meta span:nth-child(2)').textContent===select.value)&&(!tool.querySelectorAll('select')[1].value||c.querySelector('.pin')));if(!c.hidden)n++}document.getElementById('memory-count').textContent=n+' / '+cards.length+' 条'}tool.oninput=filter;tool.onchange=filter;filter()}
function makeAccessible(){document.querySelectorAll('.card[onclick],.h-item,.mc-edges .lk,.close,.mc-x,.fold,.gx-search .x,[onclick="wander(event)"]').forEach(el=>{el.tabIndex=0;el.setAttribute('role','button');el.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target===el){e.preventDefault();el.click()}}});document.querySelectorAll('#p-digest [title]').forEach(el=>{el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label',el.title);el.onclick=()=>{const n=document.getElementById('notice');n.textContent=el.title;n.style.display='block';setTimeout(()=>n.style.display='none',6000)};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click()}};el.style.background=el.style.background.replace('200, 145, 255','213, 53, 112')})}
new MutationObserver(makeAccessible).observe(document.getElementById('hits'),{childList:true});document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.getElementById('scene').style.display='none';document.getElementById('notice').style.display='none';document.getElementById('memcard').style.display='none';window.gxClearEdges?.()}});document.getElementById('scene').setAttribute('role','dialog');document.getElementById('scene').setAttribute('aria-modal','true');document.getElementById('scene').setAttribute('aria-labelledby','sc-t');makeAccessible();

const originalDiary=window.openDiary;window.openDiary=async el=>{try{await originalDiary(el)}catch(e){const box=el.querySelector('.dtext');box.textContent=e.message+'；再次展开可重试。'}};
const originalScene=window.showScene;let previousFocus=null;window.showScene=async ts=>{previousFocus=document.activeElement;try{const task=originalScene(ts);document.querySelector('#scene .close').focus();await task}catch(e){document.getElementById('sc-body').textContent=e.message}};
document.getElementById('scene').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();document.querySelector('#scene .close').focus()}});
new MutationObserver(()=>{if(document.getElementById('scene').style.display==='none'&&previousFocus?.isConnected)previousFocus.focus()}).observe(document.getElementById('scene'),{attributes:true,attributeFilter:['style']});
